# Generated by Django 4.2.7 on 2023-11-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.PositiveSmallIntegerField(default=15005004, unique=True),
            preserve_default=False,
        ),
    ]
